#!/usr/bin/env python3

import uvicorn
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse,Response
from fastapi import Request
from pydantic import BaseModel

import numpy as np
from pathlib import Path
import datetime

from w import main
from my_util_files import identify_most_recent_file

class LocationRequest(BaseModel):
    latitude: float
    longitude: float
    accuracy: float
    timestamp: int
    flag_iso: bool

class LocationResponse(BaseModel):
    html: str
    diag: str

app = FastAPI(
    docs_url=None,          # disables /docs
    redoc_url=None,         # disables /redoc
    openapi_url=None,       # disables /openapi.json
)

app.mount('/objs', StaticFiles(directory='objs'), name='objs')

@app.get('/', response_class=HTMLResponse)
async def req_catch_all(request: Request):
    html = "<html><body><h1>Home Page</h1><hr>This demonstrates that the server can be reached.</body></html>"
    return HTMLResponse(content=html)





def location_worker(user_pos, flag_iso=True):
    # datadir = Path('/home/cl/work/criticalmaps--richtungspfeil/cmdata')
    # freshest_datafile_info = identify_most_recent_file(datadir)
    # freshest_datafile = datadir / freshest_datafile_info.fn

    # generate "unique" prefix for image files
    tnow = datetime.datetime.now()
    tstr = tnow.strftime('%Y%m%dT%H%M%S.%f')
    fprefix = f'img_{tstr}_'

    # no datafile given --> use DB for current positions
    r = main(observer_pos=user_pos, obj_path=Path('/home/cl/work/criticalmaps--richtungspfeil/objs/'), fprefix=fprefix, exclude_isolated_points=flag_iso)
    # r = main(datafile=freshest_datafile, observer_pos=user_pos, obj_path=Path('/home/cl/work/criticalmaps--richtungspfeil/objs/'), fprefix=fprefix, exclude_isolated_points=flag_iso)

    diag_info = '<h3>Diag Infos</h3>'
    diag_info += f'Server time: {tstr}<br>'
    diag_info += '<ul>'
    for di in r['diag_info']:
        diag_info += '<li>'+di
    diag_info += '</ul>'


    def ci_as_table(lci):
        """
        Converts list of ClusterInfo instances to HTML table
        """
        r = "<table>\n"
        if len(lci)>0:
            r += lci[0].table_header()
            for x in lci:
                r += x.as_html() + '\n'
        else:
            r += '<tr><td>(no clusters match current criteria)</td></tr>'
        r += "</table>\n"
        return r

    ci = r['clusters']
    ci = sorted(ci, key=lambda _: (_.N,-_.dist), reverse=True) # Note: tuple as sort key -> force sort order for clusters with identical N, list closer clusters first (if first element is identical, second element determines sort order)
    ci_dist = sorted(ci, key=lambda _: _.dist, reverse=False)
    diag_info += '<h3>Clusters (lowest distance first)</h3>'
    diag_info += ci_as_table(ci_dist)
    diag_info += '<h3>Clusters (largest cluster first)</h3>'
    diag_info += ci_as_table(ci)

    # Keys of images to present FIRST (in this order)
    top_files = ['clusters_local','clusters']

    html_imgs = ""
    print(r['files'])
    def html4img(k):
        def get_img_loc(k):
            return 'api/objs/' + r['files'][k]
        return f'<img src="{ get_img_loc(k) }"><br>'
    ### top imgs
    for k in top_files:
        if not k in r['files']:
            print(f'WARNING: key {k} not found in list of files')
            continue
        html_imgs += html4img(k)
    ### all other images
    for k in r['files'].keys():
        if k in top_files:
            continue
        html_imgs += html4img(k)


    return {
        'html': '<h3>Plots generated by server</h3>'+html_imgs,
        'diag': diag_info
    }

@app.post('/location_demo', response_model=LocationResponse)
@app.get('/location_demo', response_model=LocationResponse)
def update_location_demo():
    """
    Implements location API endpoint for DEMO
    (input: does not require coordinates, uses hard-coded user-coordinates)
    """
    # fixed dummy position in Hamburg for dev/demo
    user_pos = np.array([53.55, 10.0])
    return location_worker(user_pos, flag_iso=payload.flag_iso)

@app.post('/location', response_model=LocationResponse)
def update_location(payload: LocationRequest):
    """
    Implements location API endpoint
    """
    user_pos = np.array([payload.latitude, payload.longitude])
    return location_worker(user_pos, flag_iso=payload.flag_iso)


if __name__=="__main__":
    uvicorn.run(
        app,
        host='0.0.0.0', port=8777,
        server_header=False, # <- don't send "server: uvicorn" in response
    )
