#!/usr/bin/env python3

import uvicorn
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse,Response
from fastapi import Request
from pydantic import BaseModel, field_serializer

import numpy as np
from pathlib import Path
import datetime
from zoneinfo import ZoneInfo

from critical_dir.criticaldir_core import MyAnalyzer,MyPlotter,DataLoaderDB,AlgoConfig
from critical_dir.db_conn import get_db_conn
from critical_dir.settings import get_settings
from critical_dir.exceptions import EInsufficientData
from critical_dir.wip_subclusters import generate_subclusters

class SubClustersResponseItem(BaseModel):
    N: int
    clat: float
    clon: float
    rho: float
    @field_serializer('clat','clon','rho') # use mode='plain'?
    def float_rounded(self, value: float) -> float:
        return round(value,6)

class ClustersResponseItem(BaseModel):
    cluster_ID: int
    N: int
    center_latitude: float
    center_longitude: float
    subclusters: list[SubClustersResponseItem] | None=None # field is optional (appears in returned JSON with value 'null')

    @field_serializer('center_latitude','center_longitude') # use mode='plain'?
    def float_rounded(self, value: float) -> float:
        return round(value,6)

class HistoricSubclustersItem(BaseModel):
    age: float
    subclusters: list[SubClustersResponseItem]

class ClustersResponse(BaseModel):
    info: str
    clusters: list[ClustersResponseItem]
    historic_subclusters: list[HistoricSubclustersItem] | None=None # field is optional (appears in returned JSON with value 'null')

class LocationRequest(BaseModel):
    latitude: float
    longitude: float
    accuracy: float
    timestamp: int
    cfg_flag_iso: bool
    cfg_flag_exclude_stationary: bool
    cfg_cluster_dist: float = 2   # km
    cfg_tpersistence: float = 900 # seconds

class LocationResponse(BaseModel):
    html: str
    diag: str



app = FastAPI(
    docs_url=None,          # disables /docs
    redoc_url=None,         # disables /redoc
    openapi_url=None,       # disables /openapi.json
)

# v1 of the web client is not deprecated, so /objs is not needed anymore
# app.mount('/objs', StaticFiles(directory='objs'), name='objs')

@app.get('/', response_class=HTMLResponse)
async def req_catch_all(request: Request):
    html = "<html><body><h1>Home Page</h1><hr>This demonstrates that the server can be reached.</body></html>"
    return HTMLResponse(content=html)


###############################################################################################
### /location is the main workhorse, requests from WebApp for data on overview page go here ###
###############################################################################################

def generate_simulated_clusters():
    epoch_now = int(datetime.datetime.now().timestamp())

    p0 = np.array([53.55, 10.0])
    period = 900 # seconds (should be integer)

    period = int(period)
    phase = 2*np.pi * (float(epoch_now % period)/period)
    p1 = p0 + 0.020*np.array([np.cos(phase), np.sin(phase)])
    p2 = p0 + 0.025*np.array([np.cos(-phase), np.sin(-phase)])
    p3 = p0 + 0.030*np.array([np.sin(phase), 0])

    # generate data format, emulating additional parameters
    r = []
    for idx,currp in enumerate([p1,p2,p3]):
        currID = 3*idx # because of filtering in the API server, cluster IDs can be non-contiguous
        currN = 5+2*idx
        # has to be same data format as generated by cluster worker function
        r.append({'cluster_ID':currID, 'center_latitude':currp[0], 'center_longitude':currp[1], 'N':currN})
    return r

def clusters_worker_fdev(*, res, cluster_ID, f_generate_subclusters):
    # select datapoints that are in the cluster
    data_in_cluster = []
    for d,l in zip(res.data, res.cluster_labels):
        if l==cluster_ID:
            data_in_cluster.append(d)
    # print(data_in_cluster)
    return f_generate_subclusters(data=data_in_cluster)


def clusters_worker(*, ag, min_cluster_size:int=3, t0:datetime.datetime=None, use_simulated_data=False):
    if use_simulated_data:
        return generate_simulated_clusters(),[]

    # dummy position, we only return clusters without direction information
    user_pos = np.array([53.55, 10.0])

    tnow = datetime.datetime.now(tz=ZoneInfo('Europe/Berlin')) # need to specify timezone for comparison operations
    if t0:
        if t0>tnow:
            raise ValueError('provided time-stamp is from the future')
        tnow = t0
    epoch = int(tnow.timestamp())

    # use DB to obtain position data
    my_dl = DataLoaderDB(f_factory_DBconn=get_db_conn, t0=epoch)
    my_a = MyAnalyzer(dl=my_dl)
    res = my_a.perform_analysis(observer_pos=user_pos, ag=ag)
    # print(res.cluster_infos)

    # To be JSON serializable, the returned object has to be an instance of the defined pydantic class.
    # Some of the fields that come from the analysis process should be shadowed from the client, such as course/distance because they were computed using the dummy user_position we had to provide
    # Only clusters exceeding a minimum number of members are returned to the
    # user to prevent exposing individual positions.
    def fx(analysis_result):
        r = []
        for ci in analysis_result.cluster_infos:
            if ci.N<min_cluster_size:
                continue # ignore small clusters
            # obtain subclusters
            subclusters = clusters_worker_fdev(res=analysis_result, cluster_ID=ci.cluster_ID, f_generate_subclusters=generate_subclusters)
            # print(subclusters)
            r.append({
                        'cluster_ID':ci.cluster_ID,
                        'N':ci.N, 'center_latitude':ci.latitude, 'center_longitude':ci.longitude,
                        'subclusters': subclusters
                    })
        return r

    r = fx(res)

    ages = [300,600]
    r_h = []
    for age in ages:
        if age<0:
            raise ValueError('age has to be positive')

        # If we arrive here, sufficient data was there for the time of interest
        # (typically this means "live data").
        # But it might still throw an exception signalling insufficient data
        # for any requests for historic data. An important case where this
        # becomes relevant is automatic testing of Docker images.
        # -> In these cases, execution of the function must continue.
        try:
            my_dl = DataLoaderDB(f_factory_DBconn=get_db_conn, t0=epoch-age)
            my_a = MyAnalyzer(dl=my_dl)
            res_historic = my_a.perform_analysis(observer_pos=user_pos, ag=ag)
        except EInsufficientData:
            # There is not enough data to cluster.
            # Try next set of historic data.
            continue

        # TODO: find better variable names, these are confusing: r_historic,res_historic and on the other hand r_h for the final result
        r_historic = fx(res_historic)

        # every historic cluster has a set subclusters -> join them to one big set of subclusters (this is ok as the number of clusters might have changed between the points in time and so it is not trivial to relate current and historic clusters)
        l_sc = []
        for c in r_historic:
            for _ in c['subclusters']:
                l_sc.append(_)
        r_h.append({'age':age, 'subclusters': l_sc})
    # print(r_h)
    return r, r_h

def location_worker(user_pos, *, ag):
    # store timestamp
    tic = datetime.datetime.now()

    # generate "unique" prefix for image files
    tstr = tic.strftime('%Y%m%dT%H%M%S.%f')
    fprefix = f'img_{tstr}_'

    settings = get_settings()
    def adjust_AlgoConfig(ag):
        from dataclasses import replace
        if not settings.privacy_mode:
            return ag
        # force exclusion of isolated points
        changes={'exclude_isolated_points':True}
        return replace(ag, **changes)

    # use DB for current positions
    my_dl = DataLoaderDB(f_factory_DBconn=get_db_conn)
    my_a = MyAnalyzer(dl=my_dl, obj_path=settings.img_dir, fprefix=fprefix)
    res = my_a.perform_analysis(observer_pos=user_pos, ag=adjust_AlgoConfig(ag))
    my_p = MyPlotter(
        dl=my_dl,
        obj_path=settings.img_dir, fprefix=fprefix
    )
    r = my_p.doit(res=res)


    diag_info = '<h3>Diag Infos</h3>'
    diag_info += f'Server time: {tstr}<br>'
    diag_info += '<ul>'
    for di in r['diag_info']:
        diag_info += '<li>'+di
    diag_info += '</ul>'


    def ci_as_table(lci):
        """
        Converts list of ClusterInfo instances to HTML table
        """
        r = "<table>\n"
        if len(lci)>0:
            r += lci[0].table_header()
            for x in lci:
                # generate 'inspect' link only when requested to do so (currently, the URL contains geoposition data)
                with_inspect_link = not settings.privacy_mode
                r += x.as_html(with_inspect_link=with_inspect_link) + '\n'
        else:
            r += '<tr><td><font color=red>(no clusters match current criteria)</font></td></tr>'
        r += "</table>\n"
        return r

    # ci = r['clusters']
    ci = res.cluster_infos
    ci = sorted(ci, key=lambda _: (_.N,(-1)*_.dist_km), reverse=True) # Note: tuple as sort key -> force sort order for clusters with identical N, list closer clusters first (if first element is identical, second element determines sort order)
    ci_dist = sorted(ci, key=lambda _: _.dist_km, reverse=False)
    html_info  = ''
    html_info += '<h3>Clusters (lowest distance first)</h3>'
    html_info += ci_as_table(ci_dist)
    html_info += '<h3>Clusters (largest cluster first)</h3>'
    html_info += ci_as_table(ci)

    # Keys of images to present FIRST (in this order)
    top_files = ['clusters_polar','clusters_hamburg','clusters']

    html_imgs = ""
    print(r['files'])
    def html4img(k):
        def get_img_loc(k):
            return 'api/objs/' + r['files'][k]
        return f'<img src="{ get_img_loc(k) }"><br>'
    ### top imgs
    for k in top_files:
        if not k in r['files']:
            print(f'WARNING: key {k} not found in list of files')
            continue
        html_imgs += html4img(k)
    ### all other images
    for k in r['files'].keys():
        if k in top_files:
            continue
        html_imgs += html4img(k)

    # store timestamp
    toc = datetime.datetime.now()
    deltat = toc-tic
    deltat = deltat.total_seconds()
    diag_info += f'<p>total processing time: {deltat:.2f} seconds'

    return {
        'html': html_info+'<h3>Plots generated by server</h3>'+html_imgs,
        'diag': diag_info
    }

@app.get('/clusters_demo', response_model=ClustersResponse)
def get_clusters_demo():
    clusters,_ = clusters_worker(ag=None, use_simulated_data=True)
    r = {
        # only parameters influencing the result (we enforce min cluster size -> irrelevant if isolated points are excluded by clustering algorithm or no; not using any trace persistence here)
        'info': f'd=1.0, x=True',
        'clusters': clusters
    }
    return r

@app.get('/clusters', response_model=ClustersResponse)
def get_clusters(
        # parameters with their default values (only relevant in test mode)
        maxdist: float = 1.0,
        exclstat: bool = True
    ):
    # for the demo, some hard-coded defaults
    ag = AlgoConfig(
        exclude_isolated_points=True,
        exclude_stationary_devices=True, 
        cluster_dist_thres=0.5,
        device_trace_persistence=900
    )

    # only in test mode, a value passed in the GET request becomes relevant
    settings = get_settings()
    if settings.test_mode:
        print('test mode')
        if maxdist<0:
            raise ValueError('maxdist parameter must be positive')
        if maxdist>100:
            raise ValueError('maxdist too large... ')
        from dataclasses import replace
        changes = {'cluster_dist_thres': maxdist, 'exclude_stationary_devices':exclstat}
        ag = replace(ag, **changes)

    # run clustering algorithm (and catch exception raised if there is insufficient amount of data)
    try:
        # tnow = datetime.datetime(2026,6,14, 14,49, tzinfo=ZoneInfo('Europe/Berlin')) # "Sternfahrt" in Munich, Germany
        # clusters,l_historic_subclusters = clusters_worker(ag=ag, min_cluster_size=3, t0=tnow)
        clusters,l_historic_subclusters = clusters_worker(ag=ag, min_cluster_size=3)
    except EInsufficientData:
        clusters = []
        l_historic_subclusters = []

    r = {
        # only parameters influencing the result (we enforce min cluster size -> irrelevant if isolated points are excluded by clustering algorithm or no; not using any trace persistence here)
        'info': f'd={ag.cluster_dist_thres}, x={ag.exclude_stationary_devices}',
        'clusters': clusters,
        'historic_subclusters': l_historic_subclusters
    }
    # Note: we don't include lat/long of all cluster members in response (privacy)
    return r


@app.post('/location_demo', response_model=LocationResponse)
@app.get('/location_demo', response_model=LocationResponse)
def update_location_demo():
    """
    Implements location API endpoint for DEMO
    (input: does not require coordinates, uses hard-coded user-coordinates)
    """
    # end point is deprecated (but keeping the code for now)
    return HTMLResponse('permission denied', status_code=403)

    # fixed dummy position in Hamburg for dev/demo
    user_pos = np.array([53.55, 10.0])
    ag = AlgoConfig(
        exclude_isolated_points=payload.cfg_flag_iso,
        exclude_stationary_devices=payload.cfg_flag_exclude_stationary, 
        cluster_dist_thres=payload.cfg_cluster_dist,
        device_trace_persistence=payload.cfg_tpersistence
    )
    return location_worker(user_pos, ag=ag)

@app.post('/location', response_model=LocationResponse)
def update_location(payload: LocationRequest):
    """
    Implements location API endpoint
    """
    # end point is deprecated (but keeping the code for now)
    return HTMLResponse('permission denied', status_code=403)

    user_pos = np.array([payload.latitude, payload.longitude])
    ag = AlgoConfig(
        exclude_isolated_points=payload.cfg_flag_iso,
        exclude_stationary_devices=payload.cfg_flag_exclude_stationary, 
        cluster_dist_thres=payload.cfg_cluster_dist,
        device_trace_persistence=payload.cfg_tpersistence
    )
    return location_worker(user_pos, ag=ag)


@app.get('/inspect', response_class=HTMLResponse)
async def inspect(clat: float, clong: float):
    # end point is deprecated (but keeping the code for now)
    return HTMLResponse('permission denied', status_code=403)

    settings = get_settings()

    if settings.privacy_mode:
        return HTMLResponse('permission denied', status_code=403)

    # generate "unique" prefix for image files
    tnow = datetime.datetime.now()
    tstr = tnow.strftime('%Y%m%dT%H%M%S.%f')
    fprefix = f'img_{tstr}_'

    my_dl = DataLoaderDB(f_factory_DBconn=get_db_conn)
    my_a = MyAnalyzer(dl=my_dl, obj_path=settings.img_dir, fprefix=fprefix)
    my_p = MyPlotter(
        dl=my_dl,
        obj_path=settings.img_dir, fprefix=fprefix
    )
    r = my_p.inspect_generate_img(observer_pos=[clat,clong], ag=AlgoConfig())

    fn_img = r['files']['inspect']
    html = f"<html><body><a href=/myapp/>For iPhone PWA: Back</a><p>Inspecting local distribution of riders around {clat:.4f},{clong:.4f}. Note that this plot does not indicate cluster infos, so all positions are indicated with same marker color.<img src=\"objs/{fn_img}\"></body></html>"
    return HTMLResponse(content=html)

def check_db_freshness(*, max_age = 900):
    """
    Optional arguments: maximum age in seconds.
    If data is older, this is considered an error.
    """
    my_dl = DataLoaderDB(f_factory_DBconn=get_db_conn)
    max_timestamp = my_dl.get_data_newest_timestamp()
    epoch_now = datetime.datetime.now().timestamp()
    deltat = epoch_now - max_timestamp

    # Catch any timestamps from the "future". Or the system clock is off...
    if deltat<0:
        raise ValueError('Most recent timestamp is newer than current time on server.')

    # print(f'dbg: deltat={deltat}')
    is_fresh = deltat<max_age
    return is_fresh

def health_check_core_worker(*, report_stale_db=True):
    """
    Checks the freshness of the DB in any case (as this verifies that the
    DB can be reached and that the table can be accessed).
    """
    is_fresh = check_db_freshness()
    # print(f'DB freshness --> {is_fresh}')

    # TODO: Currently NOT running a test of the cluster algorithm as it can
    # take a few seconds. One trade-off could be to cache the result of cluster
    # algorithm for (for instance) 15 minutes.
   
    # determine the result, taking everything into consideration
    is_ok = True
    if report_stale_db:
        if is_fresh==False:
            is_ok=False
    return is_ok

def health_check_worker(kwargs={}):
    is_ok = health_check_core_worker(**kwargs)
    if is_ok:
        return HTMLResponse('OK')
    r = HTMLResponse('not OK', status_code=500)
    return r


@app.get('/health', response_class=HTMLResponse)
@app.head('/health', response_class=HTMLResponse)
async def health():
    return health_check_worker()

@app.get('/health_no_freshness_check', response_class=HTMLResponse)
@app.head('/health_no_freshness_check', response_class=HTMLResponse)
async def health():
    """
    Test for Docker, does not consider DB freshness (as stale data does not prevent the
    API server from operating). This prevents a "restart storm".
    Of course, DB freshness has then to be checked with another URL monitor checking /health .
    """
    return health_check_worker(kwargs={'report_stale_db':False})

def main():
    uvicorn.run(
        app,
        host='0.0.0.0', port=8081,
        server_header=False, # <- don't send "server: uvicorn" in response
    )

if __name__=="__main__":
    main()
